---
title: "Task 4 EDS 221 Loops and Functions"
author: "Dalila Lara"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Part 1. For loops revisited 

### Task 1 
```{r}
#Create 2 sequences 
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

transects <- c("TransectA", "TransectB", "TransectC")

output <- matrix(nrow = length(weekdays), ncol = length(transects))

#Write a nested loop for loop to create a matrix for both 
for(i in seq_along(weekdays)) {
  for(j in seq_along(transects)) {
    matrix_2 <- paste0(weekdays[i], "-", transects[j])
    output[i,j] <- matrix_2
  }
}
#matrix created
output
```


# Part 2. Functions introduced
### Task 2
Create a function that returns statment with result of function.
```{r}
force <- function(m, a) {
  paste("The resulting force is ", m * a, "newtons")
} 

force(10, 5)
```

### Task 3
```{r}
# Create a data frame of fish data
sci_name <- c("Chanos chanos", "Sphyraena barracuda", "Caranc ignobilis")

common_name <- c("Milkfish", "Great barracuda", "Giant trevally")

a_est <- c(0.0905, 0.0181, 0.0353)

b_est <- c(2.52, 3.27, 3.05)

fish_parms <- data.frame(sci_name, common_name, a_est, b_est)
```

```{r}
#Write function
fish_weight <- function(name, tot_length) {
  my_subset <- filter(fish_parms, common_name == name)
  print(my_subset$a_est*tot_length^my_subset$b_est)
}

fish_weight(name = "Milkfish", 10)
```

```{r}
# Create vector and insert to function 

vector <- seq(from = 0, to = 100, by =1)

milk_fish_weights <- fish_weight( name = "Milkfish", vector)
```


### Task 4
```{r}
wave_power <- function(H, Period) {
  0.5*H^2*Period
}

wave_height <- seq(from = 0, to = 3, by = 0.2)

wave_power(wave_height, 8)



```

